version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: terraform
  directory: "/tardigrade/roots/aws/member"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: terraform
  directory: "/tardigrade/roots/aws/management"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
